spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: pgadmin
    password: somepassword
  liquibase:
    change-log: classpath:db/changelog/changelog.sql
server:
  port: 8082